export const KARATE_KEYWORDS = [
    'Feature:',
    'Scenario:',
    'Scenario Outline:',
    'Background:',
    'Given',
    'When',
    'Then',
    'And',
    'But',
    '*',
    'Examples:',
    'def',
    'path',
    'url',
    'method',
    'status',
    'request',
    'response',
    'match',
    'assert',
    'print',
    'header',
    'headers',
    'form field',
    'multipart field',
    'params',
    'param',
    'cookie',
    'configure',
    'call',
    'callonce',
    'eval',
    'table',
    'replace',
    'get',
    'post',
    'put',
    'delete',
    'patch',
    'options',
    'head',
    'set'
] as const;

export type KarateKeyword = typeof KARATE_KEYWORDS[number];

export const HOVER_INFO: Record<string, string> = {
    'Feature:': 'Description of the feature being tested',
    'Scenario:': 'A specific test case within the feature',
    'Scenario Outline:': 'A test case template with Examples',
    'Background:': 'Common steps executed before each scenario',
    'Given': 'Setup or precondition step',
    'When': 'Action step',
    'Then': 'Assertion or validation step',
    'And': 'Additional step with same context as previous',
    'But': 'Contrasting step',
    '*': 'Generic step',
    'Examples:': 'Data table for Scenario Outline',
    'def': 'Define a variable',
    'path': 'Set URL path segment',
    'url': 'Set base URL',
    'method': 'Set HTTP method',
    'status': 'Assert HTTP response status',
    'request': 'Set request body',
    'response': 'Access response body',
    'match': 'Assert response or values',
    'assert': 'Make assertions',
    'print': 'Print debug information'
};